export const SEARCH_MOVIES_BEGIN = 'SEARCH_MOVIES_BEGIN';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';
export const SEARCH_TEXT_CHANGE = 'SEARCH_TEXT_CHANGE';
export const SEARCH_BY_CHANGE = 'SEARCH_BY_CHANGE';
export const SEARCH_MOVIES_REDIRECT = 'SEARCH_MOVIES_REDIRECT';
